#!/bin/bash
# @(#) MT
# @(#) cENM check for Charts
# @(#) Version: 1.00 (09.06.2020)
# @(#) Author: SuperGMario gianmario.rossi@ericsson.com and luca.ferrari@ericsson.com
# @(#)         I am Mr "REM", I solve problems
# Parameters:
# $1 = director ip
# $2 = namespace
# $3 = deployment

# Version     Date      Changes
# -------  ----------   ------------------------------------------------------
#  1.00    09/06/2020   First release 
_RD='\033[0;31m'     # Red for "echo"
_BL='\033[0;34m'     # Blue for "echo"
_LG='\033[0;37m'     # Light Gray for "echo"
_WH='\033[1;37m'     # White for "echo"
_NC='\033[0m'        # Normal for "echo"

installationPath=`pwd`

directorIP=$1
namespace=$2
deployment=$3

echo -e "\n \n -------->   CHECKING CHARTS IN DEPLOYED STATE"

ssh -i ${deployment}.pem eccd@${directorIP} " helm3 list --all -n $namespace" 2> /dev/null > ${installationPath}/log/${deployment}.charts.`echo $(date "+%Y%m%d")`.$$
cat ${installationPath}/log/${deployment}.charts.`echo $(date "+%Y%m%d")`.$$ | grep -v 'NAME' > /tmp/Charts.$$
#ssh -i ${deployment}.pem eccd@${directorIP} " helm3 list --all -n $namespace | grep -v 'NAME'" 2> /dev/null | tee /tmp/Charts.$$ ${installationPath}/log/${deployment}.charts.`echo $(date "+%Y%m%d")`.$$ > /dev/null
charts=$(wc -l /tmp/Charts.$$ | awk '{ print $1 }')
if [ "$charts" -gt 0 ]; then
    deployed_charts=$(cat /tmp/Charts.$$ | grep -c deployed)
    not_deployed_charts=$(cat /tmp/Charts.$$ | grep -c -v deployed)
    if [ "$not_deployed_charts" -gt 0 ]; then
        echo -e "\n ${_RD} These charts are not in deployed state ${_NC} \n"
        cat /tmp/Charts.$$ | grep -v deployed
    else
        echo -e "\n all the charts are in deployed state"
    fi
    echo -e "\n $deployed_charts charts on $charts are in deployed state"
else
    echo -e "\n \n ${_RD} no charts are present for this deployment${_NC}"
    rm -f /tmp/Charts.$$
    exit 1
fi

rm -f /tmp/Charts.$$
exit 0




#kubectl get pods -o wide -n enm33 | grep -v Completed | awk '{ print $1 }' > /tmp/notCompletedPod.$$

#while read LINE; do
#    kubectl describe pods $LINE -n $namespace | grep True
#    if [] ; then
#        echo "Pod $LINE is not in ready state"
#    fi
#done < /tmp/notCompletedPod.$$
